# FROM node
FROM node:20.9.0-alpine3.18

WORKDIR /frontend

COPY . .
#pnpm i yapmadan önce pnpm yoksa diye npm den önce onu indirsin diyoruz
RUN npm i -g pnpm
RUN pnpm i

CMD ["npm", "start"]
# VITE nin port u 5173
EXPOSE 5173

# --------------------------------
# $ cd /frontend
# $ docker build -t frontend .
# $ docker run -p 5173:5173 --name frontend frontend
# $ docker run -d -p 5173:5173 --name frontend frontend
# $ docker run -d -p 80:5173 --name frontend80 qadiradamson/frontend
# Browser: http://localhost:5173