# Altyapı (from dockerHub):
#alpine bir linux tabanli image  yani ben FROM node:alpine deyince linux üde cagirmis olacagim
FROM node:20.9.0-alpine
# Çalışma Alanı:Bu klasörü kullanacagim
WORKDIR /app
# Dosyaları Aktar: COPY local inImage
# COPY hello.js /app
COPY . .

# After build (when image to container):
# docker run imagename
CMD node hello.js
